version: '3.9'

services:
  wikiri_db1:
    container_name: wikiri_db1
    image: mysql:5.7
    volumes:
      - ./db_data1:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    platform: linux/x86_64

  wikiri_wordpress1:
    container_name: wikiri_wordpress1
    image: wordpress:latest
    restart: always
    volumes:
      - ./wordpress1:/var/www/html
    environment:
      WORDPRESS_DB_HOST: wikiri_db1
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    ports:
      - "8080:80"



