version: '3.9'

services:
  db1:
    image: mysql:5.7
    volumes:
      - db1_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress1
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    platform: linux/x86_64

  db2:
    image: mysql:5.7
    volumes:
      - db2_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress2
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    platform: linux/x86_64

  db3:
    image: mysql:5.7
    volumes:
      - db3_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress3
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    platform: linux/x86_64

  wordpress1:
    image: wordpress:latest
    restart: always
    volumes:
      - ./wordpress1:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db1:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    ports:
      - "8080:80"

  wordpress2:
    image: wordpress:latest
    restart: always
    volumes:
      - ./wordpress2:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db2:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    ports:
      - "8081:80"

  wordpress3:
    image: wordpress:latest
    restart: always
    volumes:
      - ./wordpress3:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db3:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    ports:
      - "8082:80"

volumes:
  db1_data:
  db2_data:
  db3_data:
